# Cloud Build configuration per DockerClaw Backend
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dockerclaw-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dockerclaw-backend:latest'
      - '.'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dockerclaw-backend:$SHORT_SHA'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dockerclaw-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dockerclaw-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dockerclaw-backend:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/dockerclaw-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/dockerclaw-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
